### ISSUE TITLE
Bug: lldap baseDN

### ISSUE THREAD

**Issue by xeoneox** [djjudas21/charts#100]
### Describe the bug a clear and concise description of what the bug is.

Cannot set BaseDN string manually

### What's your helm version?

version.BuildInfo{Version:"3.16.2", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.23.1"}

### What's your kubectl version?

v1.31.1

### Which chart?

lldap

### What's the chart version?

lldap-0.3.7

### What happened?

lldap refuses to start up if the base DN string is set from the command line to anything other than the default value

### What you expected to happen?

lldap to start with the appropriate baseDN

### How to reproduce it?

helm install set lldap.baseDN=

### Enter the command that you execute and failing/misfunctioning.

helm install set lldap.baseDN=

**Comment by djjudas21** [comment]
Hey, thanks for reporting. Can you include the error message you get?

**Comment by xeoneox** [comment]
Apologies, looks like a red herring. My issues were with Terraform interpolating Helm. There were two layers of string interpolation. The solution was an extra "\" like so:

  set {
  	name  = "lldap.baseDN"
  	value = <<-EOT
  	  dc=example\,dc=org
  	EOT
  }

Thanks for the prompt response, please close
