### ISSUE TITLE
Bookstack Image Version

### ISSUE THREAD

**Issue by pagey101** [djjudas21/charts#35]
### Is your feature request related to a problem ?

Hi, thanks for taking the Bookstack chart on.

Could the image be bumped? 23.02.1 is available on docker hub.

Thanks!

### Describe the solution you'd like.

Bump image version.

### Describe alternatives you've considered.

NONE

**Comment by djjudas21** [comment]
Thanks for the nudge :slightly_smiling_face: I'm subscribed to repo notifications but I must have missed this one! I've just pushed an update to the chart with this update. 

Fixed in 178ac7b6c5b12d490282d1eaf699457a89460caa
