### ISSUE TITLE
uptime-kuma chart is broken

### ISSUE THREAD

**Issue by reitermarkus** [djjudas21/charts#43]
### Describe the bug a clear and concise description of what the bug is.

`uptime-kuma 1.5.8` uses `common 1.0.0`, which renamed `common.values.setup` to `bjw-s.common.loader.init` and `common.all` to `bjw-s.common.loader.generate`.

### What's your helm version?

v3.12.0

### What's your kubectl version?

v1.27.2

### Which chart?

uptime-kuma

### What's the chart version?

1.5.8

### What happened?

```
Error: INSTALLATION FAILED: template: uptime-kuma/templates/common.yaml:2:4: executing "uptime-kuma/templates/common.yaml" at <include "common.values.setup" .>: error calling include: template: no template "common.values.setup" associated with template "gotpl"
```

### Enter the command that you execute and failing/misfunctioning.

helm install uptime-kuma djjudas21/uptime-kuma

**Comment by djjudas21** [comment]
Sorry I didn't see this @reitermarkus. Thanks to @docbobo for fixing it
