### ISSUE TITLE
[photoprism] Helm install/upgrade does not work with mariadb sub-chart

### ISSUE THREAD

**Issue by kor-ren** [djjudas21/charts#75]
### Describe the bug a clear and concise description of what the bug is.

If i want install photoprism with mariadb, the command fails:

Command:

```shell
helm template djjudas21/photoprism  --version 7.4.14 --set maria
db.enabled=true
```

Output:

```
install.go:173: [debug] Original chart version: "7.4.14"
install.go:190: [debug] CHART PATH: /home/rene/.cache/helm/repository/photoprism-7.4.14.tgz


Error: parse error at (photoprism/charts/mariadb/charts/common/templates/_resources.tpl:15): unclosed action
helm.go:81: [debug] parse error at (photoprism/charts/mariadb/charts/common/templates/_resources.tpl:15): unclosed action
```

Last working version is `7.4.9`

### What's your helm version?

version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

### What's your kubectl version?

v1.28.7+k3s1

### Which chart?

photoprism

### What's the chart version?

7.4.14

### What happened?

Install / upgrade is not possible if mariadb is enabled

### What you expected to happen?

Install / upgrade works again

### How to reproduce it?

helm template djjudas21/photoprism  --version 7.4.14 --set mariadb.enabled=true

### Enter the command that you execute and failing/misfunctioning.

helm template djjudas21/photoprism  --version 7.4.14 --set mariadb.enabled=true --debug

**Comment by djjudas21** [comment]
Hey, thanks for your bug report.

I can't reproduce this but I notice that your version of Helm is older than mine - I'm running `v3.15.2` and you're on `v3.5.2`. Please could you try updating your Helm version?

I also have a theory that your problem is being caused by the usage of `helm template` without explicitly setting a name

```
Usage:  helm template [NAME] [CHART] [flags]
```

Please can you also try deploying with the optional name set, for example

```
helm template myphotoprism djjudas21/photoprism --version 7.4.14 --set mariadb.enabled=true
```

**Comment by kor-ren** [comment]
Thank you for the fast answer , I will try it with a higher helm version later.

As info: I get the same error with install or upgrade (with name) instead of template

**Comment by kor-ren** [comment]
Upgrading helm has solved the issue. Thanks,
Had not in mind that my helm version was old.

**Comment by djjudas21** [comment]
I don't know what OS you're on, or how you're installing helm, but if you install brew/homebrew, then it will keep helm up to date with a package manager 🙂 I just run `brew update` once in a while.
