### ISSUE TITLE
External Database support for LLDAP

### ISSUE THREAD

**Issue by flashpixx** [djjudas21/charts#78]
### Is your feature request related to a problem ?

Yes, because I'm using the Helm chart for an centalized authentification service of another project, which ships also with Postgres, I didn't want to run multiple postgres instances

### Describe the solution you'd like.

Extend the chart so that any kind of external databases can be used, e.g. multiple section `externalPostgres` or `externalMariaDB` could be used, if one of these is set, the settings will be used, with that my external database can be used

### Describe alternatives you've considered.

NONE

**Comment by djjudas21** [comment]
Hey, thanks for your suggestion. Which helm chart is your request about? I'm assuming lldap if this is related to authentication?

**Comment by flashpixx** [comment]
yes it is the lldap chart, I have got an external Postgresql database so I have to pass the connection settings oly to the chart and need to disable the built-in chart.

**Comment by djjudas21** [comment]
Thanks for clarifying. I agree it would be a useful feature. I'm away from work for 2 weeks but I'll have a look at this when I'm back. In the meantime I'm always happy to receive pull requests 🙂

**Comment by flashpixx** [comment]
I have tested it locally with my setup
