### ISSUE TITLE
jellyfin and other charts

### ISSUE THREAD

**Issue by emouawad** [djjudas21/charts#88]
### Describe the bug a clear and concise description of what the bug is.

On Google GKE:
```log
chart requires kubeVersion: >=1.20 which is incompatible with Kubernetes v1.30.3-gke.1969001
```

For better compatibility with GKE charts can use this format: 
`kubeVersion: ">=1.22.0-0"`

Other example working charts on GKE:
https://github.com/plcnk/charts/blob/master/charts/it-tools/Chart.yaml

### What's your helm version?

v3.15.2

### What's your kubectl version?

v1.28.12

### Which chart?

jellyfin 

### What's the chart version?

3.1.8

### Enter the command that you execute and failing/misfunctioning.

helm install my-jellyfin djjudas21/jellyfin --version 3.1.8

**Comment by djjudas21** [comment]
Thanks for reporting. I'm looking now

**Comment by djjudas21** [comment]
Looks like Jellyfin was the only chart in my repo with the old syntax, the rest were OK. Let me know if it's still not working for you :slightly_smiling_face:
